### ISSUE TITLE
CTA:  Admin Redirect to the Admin Main Page (UI Skeleton)

### ISSUE THREAD

**Issue by fkangaye** [mgalde/Cybertrust_Admin#19]
As a Cybertrust Admin
I want to be redirected to The Admin Main Page
So that I can manage all the Cybertrust Users surveys and completeness status

Requirements:
Given I am an Admin
When I on the Admin Main Page
Then I see a side nav

Given I am an Admin
When I on the Admin Main Page
Then the side nav have UserList , DashBoard, Settings, Surveys

Given I am an Admin
When I click on the UserList
Then the right(main page) load the **User List Page** with Header **User List**

Given I am an Admin
When I click on the Surveys
Then the right(main page) load the **Survey List Page** with Header **Surveys**

Given I am an Admin
When I click on the Settings
Then the right(main page) load the **Setting Page**  with Header **Settings**

Given I am an Admin
When I click on the DashBoard
Then the right(main page) load the **Admin DashBoard Page** with Header **DashBoard**

- These new pages (Component) will not hold any data.
- Will need to generate these new templates for UserListPage, SettingPage, AdminDashBoardPage, ect..

**Design:** 

<img width="1060" alt="screen shot 2019-02-20 at 4 46 35 pm" src="https://user-images.githubusercontent.com/12779290/53130232-480c2000-352f-11e9-8b0f-bb04718ea37d.png">

**Comment by taraka-vishnumolakala** [comment]
@fkangaye @mgalde @AustinNielsen @jarob00 

**This is our current admin page. Do we still need this ticket?** 

<img width="1552" alt="screen shot 2019-02-22 at 7 35 54 pm" src="https://user-images.githubusercontent.com/31106457/53503230-48e40b00-3a75-11e9-9b8c-5ceae984d9a8.png">

**Comment by mgalde** [comment]
So we need to add more to the page and build it up, this needs to be broken down into additional tasks. We can talk about this tomorrow
