### ISSUE TITLE
CTU: User Detail Page with List of Surveys

### ISSUE THREAD

**Issue by fkangaye** [mgalde/Cybertrust_Admin#20]
As a Cybertrust User
I want the ability to view my list of surveys
So that I can select a survey and see the details of the selected survey

Requirements:

Given I am on the User Detail Page
When I have a list of Surveys in a table format
Then each row has a **Experiment**, **Short Description**, Action(**Start | Continue| View**) and **Score**

Given I am on the User Detail Page
When I click on Action **"Start"** or **"Continue"**
Then I am redirected to the Existing Cybertrust Survey Page to take the survey

Given I am on the User Detail Page
When I click on Action "View"
Then I am redirected to the New Survey Detail Page.

**Design:**

![screen shot 2019-02-19 at 12 18 03 am](https://user-images.githubusercontent.com/12779290/52994200-6e6d7680-33dc-11e9-8163-2e749890b7dc.png)

**Comment by mgalde** [comment]
Maybe this ticket should also show what answers were correct vs. incorrect
