### ISSUE TITLE
What does the user need to do?

### ISSUE THREAD

**Issue by mgalde** [mgalde/Cybertrust_Admin#30]

**Comment by taraka-vishnumolakala** [comment]
View results
View Upcoming tests
Get more training or practice tests -- may be these tests don't count towards his scores
Look for correct answers from his previous tests -- this might be a good feature ??
@mgalde @fkangaye @AustinNielsen @jarob00

**Comment by mgalde** [comment]
I was farming out ideas, want to make sure I am not missing anything obvious
