### ISSUE TITLE
CTU: Navigation Bar

### ISSUE THREAD

**Issue by taraka-vishnumolakala** [mgalde/Cybertrust_Admin#38]
### User Story: 
As a *USER* I want a *TOP NAVIGATION BAR ON ALL PAGES* so that I can *EASILY MOVE BETWEEN DIFFERENT VIEWS*.

### Requirements: 

- [x] Make the Navigation bar static for all pages

- [x] Create a HOME button on the top left corner of the page

- [x] Create a LOGOUT/SIGN OFF button on the top right corner. 

- [x] Create a button SCORES for a detailed results page with all the scores

- [x] Create a PROFILE management button to update personal information.

**Comment by mgalde** [comment]
![image](https://user-images.githubusercontent.com/30883926/53121121-0f614c00-3519-11e9-9175-b24b86ab0675.png)
Scores and Profile still needed 

![image](https://user-images.githubusercontent.com/30883926/53121137-1a1be100-3519-11e9-8dcc-91251e9c0027.png)

Taskbar updated with last build 
https://github.com/MLHale/cybertrust-builds/commit/8d3f225e4b20848c5804716b604153119780fb2c

**Comment by mgalde** [comment]
Added Nav Bar Components 

![image](https://user-images.githubusercontent.com/30883926/53538246-7d39e480-3ad2-11e9-8ac7-2e092d86dc67.png)


* Logged in User
![image](https://user-images.githubusercontent.com/30883926/53538258-90e54b00-3ad2-11e9-8262-3c9e693fea20.png)

Scores Template for linking
![image](https://user-images.githubusercontent.com/30883926/53538273-9cd10d00-3ad2-11e9-9069-8844990110b6.png)

Profile template for linking
![image](https://user-images.githubusercontent.com/30883926/53538280-a8bccf00-3ad2-11e9-83d1-c82edc9ff118.png)

**Comment by mgalde** [comment]
Non logged in user
![image](https://user-images.githubusercontent.com/30883926/53538341-e0c41200-3ad2-11e9-8c48-f7794391ad27.png)
