### ISSUE TITLE
CTU: Table view of all my test scores

### ISSUE THREAD

**Issue by taraka-vishnumolakala** [mgalde/Cybertrust_Admin#40]
### User Story: 
As a *USER* I want a *TABLE VIEW OF ALL MY SCORES* so that I can *CHECK MY PAST TEST RESULTS*

### Requirements: 

- [ ] Get results model for the respective user 

- [ ] Table view of all scores with timestamps

**Comment by fkangaye** [comment]
Duplicate with https://github.com/mgalde/Cybertrust_Admin/issues/20
