### ISSUE TITLE
CTA: User List Page

### ISSUE THREAD

**Issue by fkangaye** [mgalde/Cybertrust_Admin#49]
As a Cybertrust Admin
I want the ability to view my list of User
So that I can select a User
And be redirected to a Detail View of that User

Requirements:

Given I am on the User List Page
When I have a list of User in a table format
Then each row has a **UserName**, **Survey Numbers**,  **Last Login** , **Messages From Admin**, **Victimization Rate** , **Improvement** (as badge)

Given I am on the User Detail Page
When I click on a User Row
Then I am redirected to the **User Detail Page**

Given I am on the User Detail Page
When I click on the improvement Rate sorting icon
Then the table is sorted from the user with the highest improvement Rate to the lowest Improvement Rate

**Design**

![screen shot 2019-02-19 at 10 58 12 pm](https://user-images.githubusercontent.com/12779290/53067488-f6658600-3499-11e9-8bac-fc244f862ab5.png)

**Comment by taraka-vishnumolakala** [comment]
@fkangaye Is it ok if I start working on this?

**Comment by mgalde** [comment]
Sure

**Comment by taraka-vishnumolakala** [comment]
I'll assign it myself once I get confirmation from @fkangaye.
